# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wdgFoto.ui'
#
# Created: Sat Mar 12 02:06:31 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(589, 445)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.FILENAME = QtGui.QLineEdit(Form)
        self.FILENAME.setReadOnly(True)
        self.FILENAME.setObjectName("FILENAME")
        self.gridLayout.addWidget(self.FILENAME, 0, 1, 1, 2)
        self.IMAGE = PicViewer(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IMAGE.sizePolicy().hasHeightForWidth())
        self.IMAGE.setSizePolicy(sizePolicy)
        self.IMAGE.setMinimumSize(QtCore.QSize(280, 210))
        self.IMAGE.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.IMAGE.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.IMAGE.setObjectName("IMAGE")
        self.gridLayout.addWidget(self.IMAGE, 1, 0, 2, 2)
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.GEOREF_PROIET_X = QtGui.QLineEdit(self.groupBox)
        self.GEOREF_PROIET_X.setObjectName("GEOREF_PROIET_X")
        self.gridLayout_2.addWidget(self.GEOREF_PROIET_X, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.GEOREF_PROIET_Y = QtGui.QLineEdit(self.groupBox)
        self.GEOREF_PROIET_Y.setObjectName("GEOREF_PROIET_Y")
        self.gridLayout_2.addWidget(self.GEOREF_PROIET_Y, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 1, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.GEOREF_EPSG4326_X = QtGui.QLineEdit(self.groupBox_2)
        self.GEOREF_EPSG4326_X.setObjectName("GEOREF_EPSG4326_X")
        self.gridLayout_3.addWidget(self.GEOREF_EPSG4326_X, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.GEOREF_EPSG4326_Y = QtGui.QLineEdit(self.groupBox_2)
        self.GEOREF_EPSG4326_Y.setObjectName("GEOREF_EPSG4326_Y")
        self.gridLayout_3.addWidget(self.GEOREF_EPSG4326_Y, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.ZZ_FRONTE_EDIFICIOID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_FRONTE_EDIFICIOID.sizePolicy().hasHeightForWidth())
        self.ZZ_FRONTE_EDIFICIOID.setSizePolicy(sizePolicy)
        self.ZZ_FRONTE_EDIFICIOID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_FRONTE_EDIFICIOID.setObjectName("ZZ_FRONTE_EDIFICIOID")
        self.gridLayout.addWidget(self.ZZ_FRONTE_EDIFICIOID, 3, 1, 1, 2)
        self.label = QtGui.QLabel(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.ANNOTAZIONE = QtGui.QPlainTextEdit(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ANNOTAZIONE.sizePolicy().hasHeightForWidth())
        self.ANNOTAZIONE.setSizePolicy(sizePolicy)
        self.ANNOTAZIONE.setObjectName("ANNOTAZIONE")
        self.gridLayout.addWidget(self.ANNOTAZIONE, 5, 0, 1, 3)
        self.SCHEDA_EDIFICIOID = QtGui.QLineEdit(Form)
        self.SCHEDA_EDIFICIOID.setObjectName("SCHEDA_EDIFICIOID")
        self.gridLayout.addWidget(self.SCHEDA_EDIFICIOID, 6, 0, 1, 3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Georef EPSG:3003", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Georef EPSG:4326", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "X", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Fronte edificio", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Annotazione", None, QtGui.QApplication.UnicodeUTF8))

from ..Utils import PicViewer
