# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wdgInterventi.ui'
#
# Created: Mon Oct 29 17:53:39 2012
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(541, 407)
        self.gridLayout_3 = QtGui.QGridLayout(Form)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 15, 0, 1, 1)
        self.SCHEDA_EDIFICIOID = QtGui.QLineEdit(Form)
        self.SCHEDA_EDIFICIOID.setObjectName(_fromUtf8("SCHEDA_EDIFICIOID"))
        self.gridLayout_3.addWidget(self.SCHEDA_EDIFICIOID, 16, 0, 1, 2)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.EPOCA_COSTRUTTIVA = GrpEpocaCostruttiva(Form)
        self.EPOCA_COSTRUTTIVA.setObjectName(_fromUtf8("EPOCA_COSTRUTTIVA"))
        self.gridLayout_3.addWidget(self.EPOCA_COSTRUTTIVA, 14, 0, 1, 2)
        self.ZZ_TIPO_INTERVENTOID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_TIPO_INTERVENTOID.sizePolicy().hasHeightForWidth())
        self.ZZ_TIPO_INTERVENTOID.setSizePolicy(sizePolicy)
        self.ZZ_TIPO_INTERVENTOID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_TIPO_INTERVENTOID.setObjectName(_fromUtf8("ZZ_TIPO_INTERVENTOID"))
        self.gridLayout_3.addWidget(self.ZZ_TIPO_INTERVENTOID, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.ZZ_NORMATIVA_SISMICAID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_NORMATIVA_SISMICAID.sizePolicy().hasHeightForWidth())
        self.ZZ_NORMATIVA_SISMICAID.setSizePolicy(sizePolicy)
        self.ZZ_NORMATIVA_SISMICAID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_NORMATIVA_SISMICAID.setObjectName(_fromUtf8("ZZ_NORMATIVA_SISMICAID"))
        self.gridLayout_3.addWidget(self.ZZ_NORMATIVA_SISMICAID, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.DESCRIZ_INTERV = QtGui.QLineEdit(Form)
        self.DESCRIZ_INTERV.setMaxLength(2000)
        self.DESCRIZ_INTERV.setObjectName(_fromUtf8("DESCRIZ_INTERV"))
        self.gridLayout_3.addWidget(self.DESCRIZ_INTERV, 3, 1, 1, 1)
        self.INTERVENTO_IN_CORSO = QtGui.QCheckBox(Form)
        self.INTERVENTO_IN_CORSO.setObjectName(_fromUtf8("INTERVENTO_IN_CORSO"))
        self.gridLayout_3.addWidget(self.INTERVENTO_IN_CORSO, 4, 0, 1, 1)
        self.titoloAbilitativoGroup = QtGui.QGroupBox(Form)
        self.titoloAbilitativoGroup.setChecked(False)
        self.titoloAbilitativoGroup.setObjectName(_fromUtf8("titoloAbilitativoGroup"))
        self.gridLayout = QtGui.QGridLayout(self.titoloAbilitativoGroup)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_5 = QtGui.QLabel(self.titoloAbilitativoGroup)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.TITOLO_ABILITATIVO = QtGui.QLineEdit(self.titoloAbilitativoGroup)
        self.TITOLO_ABILITATIVO.setMaxLength(60)
        self.TITOLO_ABILITATIVO.setObjectName(_fromUtf8("TITOLO_ABILITATIVO"))
        self.gridLayout.addWidget(self.TITOLO_ABILITATIVO, 0, 1, 1, 1)
        self.DATA_TITOLO_ABILITATIVO = QtGui.QDateEdit(self.titoloAbilitativoGroup)
        self.DATA_TITOLO_ABILITATIVO.setDate(QtCore.QDate(2000, 9, 1))
        self.DATA_TITOLO_ABILITATIVO.setCalendarPopup(True)
        self.DATA_TITOLO_ABILITATIVO.setObjectName(_fromUtf8("DATA_TITOLO_ABILITATIVO"))
        self.gridLayout.addWidget(self.DATA_TITOLO_ABILITATIVO, 0, 4, 1, 1)
        self.DATA_TITOLO_ABILITATIVO_check = QtGui.QCheckBox(self.titoloAbilitativoGroup)
        self.DATA_TITOLO_ABILITATIVO_check.setChecked(True)
        self.DATA_TITOLO_ABILITATIVO_check.setObjectName(_fromUtf8("DATA_TITOLO_ABILITATIVO_check"))
        self.gridLayout.addWidget(self.DATA_TITOLO_ABILITATIVO_check, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.titoloAbilitativoGroup, 5, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.ANNO_PROGETTAZIONE_check = QtGui.QCheckBox(self.groupBox_2)
        self.ANNO_PROGETTAZIONE_check.setChecked(True)
        self.ANNO_PROGETTAZIONE_check.setObjectName(_fromUtf8("ANNO_PROGETTAZIONE_check"))
        self.gridLayout_2.addWidget(self.ANNO_PROGETTAZIONE_check, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.ZZ_QUALITA_INFORMAZIONEID = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_QUALITA_INFORMAZIONEID.sizePolicy().hasHeightForWidth())
        self.ZZ_QUALITA_INFORMAZIONEID.setSizePolicy(sizePolicy)
        self.ZZ_QUALITA_INFORMAZIONEID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_QUALITA_INFORMAZIONEID.setObjectName(_fromUtf8("ZZ_QUALITA_INFORMAZIONEID"))
        self.gridLayout_2.addWidget(self.ZZ_QUALITA_INFORMAZIONEID, 1, 1, 1, 2)
        self.ANNO_PROGETTAZIONE = QtGui.QSpinBox(self.groupBox_2)
        self.ANNO_PROGETTAZIONE.setMinimum(1000)
        self.ANNO_PROGETTAZIONE.setMaximum(2100)
        self.ANNO_PROGETTAZIONE.setProperty(_fromUtf8("value"), 2000)
        self.ANNO_PROGETTAZIONE.setObjectName(_fromUtf8("ANNO_PROGETTAZIONE"))
        self.gridLayout_2.addWidget(self.ANNO_PROGETTAZIONE, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 6, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QObject.connect(self.DATA_TITOLO_ABILITATIVO_check, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.DATA_TITOLO_ABILITATIVO.setEnabled)
        QtCore.QObject.connect(self.ANNO_PROGETTAZIONE_check, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ANNO_PROGETTAZIONE.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Categoria di intervento", None, QtGui.QApplication.UnicodeUTF8))
        self.EPOCA_COSTRUTTIVA.setTitle(QtGui.QApplication.translate("Form", "Epoca di impianto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Normativa sismica di riferimento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Descrizione dell\'intervento", None, QtGui.QApplication.UnicodeUTF8))
        self.INTERVENTO_IN_CORSO.setText(QtGui.QApplication.translate("Form", "Intervento in corso", None, QtGui.QApplication.UnicodeUTF8))
        self.titoloAbilitativoGroup.setTitle(QtGui.QApplication.translate("Form", "Titolo abilitativo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Num.", None, QtGui.QApplication.UnicodeUTF8))
        self.DATA_TITOLO_ABILITATIVO.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.DATA_TITOLO_ABILITATIVO_check.setText(QtGui.QApplication.translate("Form", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Anno presunto di progetto", None, QtGui.QApplication.UnicodeUTF8))
        self.ANNO_PROGETTAZIONE_check.setText(QtGui.QApplication.translate("Form", "Anno progettazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Qualità dell\'informazione", None, QtGui.QApplication.UnicodeUTF8))

from ..GrpEpocaCostruttiva import GrpEpocaCostruttiva
