# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wdgInterventi.ui'
#
# Created: Thu Jan 13 14:29:11 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 407)
        self.gridLayout_3 = QtGui.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 15, 0, 1, 1)
        self.SCHEDA_EDIFICIOID = QtGui.QLineEdit(Form)
        self.SCHEDA_EDIFICIOID.setObjectName("SCHEDA_EDIFICIOID")
        self.gridLayout_3.addWidget(self.SCHEDA_EDIFICIOID, 16, 0, 1, 2)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 1)
        self.EPOCA_COSTRUTTIVA = GrpEpocaCostruttiva(Form)
        self.EPOCA_COSTRUTTIVA.setObjectName("EPOCA_COSTRUTTIVA")
        self.gridLayout_3.addWidget(self.EPOCA_COSTRUTTIVA, 14, 0, 1, 2)
        self.ZZ_TIPO_INTERVENTOID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_TIPO_INTERVENTOID.sizePolicy().hasHeightForWidth())
        self.ZZ_TIPO_INTERVENTOID.setSizePolicy(sizePolicy)
        self.ZZ_TIPO_INTERVENTOID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_TIPO_INTERVENTOID.setObjectName("ZZ_TIPO_INTERVENTOID")
        self.gridLayout_3.addWidget(self.ZZ_TIPO_INTERVENTOID, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 0, 1, 1)
        self.ZZ_NORMATIVA_SISMICAID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_NORMATIVA_SISMICAID.sizePolicy().hasHeightForWidth())
        self.ZZ_NORMATIVA_SISMICAID.setSizePolicy(sizePolicy)
        self.ZZ_NORMATIVA_SISMICAID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_NORMATIVA_SISMICAID.setObjectName("ZZ_NORMATIVA_SISMICAID")
        self.gridLayout_3.addWidget(self.ZZ_NORMATIVA_SISMICAID, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.DESCRIZ_INTERV = QtGui.QLineEdit(Form)
        self.DESCRIZ_INTERV.setMaxLength(2000)
        self.DESCRIZ_INTERV.setObjectName("DESCRIZ_INTERV")
        self.gridLayout_3.addWidget(self.DESCRIZ_INTERV, 3, 1, 1, 1)
        self.INTERVENTO_IN_CORSO = QtGui.QCheckBox(Form)
        self.INTERVENTO_IN_CORSO.setObjectName("INTERVENTO_IN_CORSO")
        self.gridLayout_3.addWidget(self.INTERVENTO_IN_CORSO, 4, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.TITOLO_ABILITATIVO = QtGui.QLineEdit(self.groupBox)
        self.TITOLO_ABILITATIVO.setMaxLength(60)
        self.TITOLO_ABILITATIVO.setObjectName("TITOLO_ABILITATIVO")
        self.gridLayout.addWidget(self.TITOLO_ABILITATIVO, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setIndent(40)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.DATA_TITOLO_ABILITATIVO = QtGui.QDateEdit(self.groupBox)
        self.DATA_TITOLO_ABILITATIVO.setCalendarPopup(True)
        self.DATA_TITOLO_ABILITATIVO.setDate(QtCore.QDate(2000, 9, 1))
        self.DATA_TITOLO_ABILITATIVO.setObjectName("DATA_TITOLO_ABILITATIVO")
        self.gridLayout.addWidget(self.DATA_TITOLO_ABILITATIVO, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 5, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.ANNO_PROGETTAZIONE = QtGui.QDateEdit(self.groupBox_2)
        self.ANNO_PROGETTAZIONE.setObjectName("ANNO_PROGETTAZIONE")
        self.gridLayout_2.addWidget(self.ANNO_PROGETTAZIONE, 0, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.ZZ_QUALITA_INFORMAZIONEID = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_QUALITA_INFORMAZIONEID.sizePolicy().hasHeightForWidth())
        self.ZZ_QUALITA_INFORMAZIONEID.setSizePolicy(sizePolicy)
        self.ZZ_QUALITA_INFORMAZIONEID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_QUALITA_INFORMAZIONEID.setObjectName("ZZ_QUALITA_INFORMAZIONEID")
        self.gridLayout_2.addWidget(self.ZZ_QUALITA_INFORMAZIONEID, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 6, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Categoria di intervento", None, QtGui.QApplication.UnicodeUTF8))
        self.EPOCA_COSTRUTTIVA.setTitle(QtGui.QApplication.translate("Form", "Epoca di impianto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Normativa sismica di riferimento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Descrizione dell\'intervento", None, QtGui.QApplication.UnicodeUTF8))
        self.INTERVENTO_IN_CORSO.setText(QtGui.QApplication.translate("Form", "Intervento in corso", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Titolo abilitativo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Num.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.DATA_TITOLO_ABILITATIVO.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Anno presunto di progetto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Anno progettazione", None, QtGui.QApplication.UnicodeUTF8))
        self.ANNO_PROGETTAZIONE.setDisplayFormat(QtGui.QApplication.translate("Form", "yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Qualità dell\'informazione", None, QtGui.QApplication.UnicodeUTF8))

from ..GrpEpocaCostruttiva import GrpEpocaCostruttiva
