# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wdgInterventi.ui'
#
# Created: Wed Jan 12 21:35:15 2011
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(541, 413)
        self.gridLayout_3 = QtGui.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.EPOCA_COSTRUTTIVA = GrpEpocaCostruttiva(Form)
        self.EPOCA_COSTRUTTIVA.setObjectName("EPOCA_COSTRUTTIVA")
        self.gridLayout_3.addWidget(self.EPOCA_COSTRUTTIVA, 0, 0, 1, 2)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.ANNO_PROGETTAZIONE = QtGui.QDateEdit(Form)
        self.ANNO_PROGETTAZIONE.setObjectName("ANNO_PROGETTAZIONE")
        self.gridLayout_3.addWidget(self.ANNO_PROGETTAZIONE, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 2, 0, 1, 1)
        self.ZZ_QUALITA_INFORMAZIONEID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_QUALITA_INFORMAZIONEID.sizePolicy().hasHeightForWidth())
        self.ZZ_QUALITA_INFORMAZIONEID.setSizePolicy(sizePolicy)
        self.ZZ_QUALITA_INFORMAZIONEID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_QUALITA_INFORMAZIONEID.setObjectName("ZZ_QUALITA_INFORMAZIONEID")
        self.gridLayout_3.addWidget(self.ZZ_QUALITA_INFORMAZIONEID, 2, 1, 1, 1)
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 5, 0, 1, 1)
        self.ZZ_TIPO_INTERVENTOID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_TIPO_INTERVENTOID.sizePolicy().hasHeightForWidth())
        self.ZZ_TIPO_INTERVENTOID.setSizePolicy(sizePolicy)
        self.ZZ_TIPO_INTERVENTOID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_TIPO_INTERVENTOID.setObjectName("ZZ_TIPO_INTERVENTOID")
        self.gridLayout_3.addWidget(self.ZZ_TIPO_INTERVENTOID, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 6, 0, 1, 1)
        self.ZZ_NORMATIVA_SISMICAID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_NORMATIVA_SISMICAID.sizePolicy().hasHeightForWidth())
        self.ZZ_NORMATIVA_SISMICAID.setSizePolicy(sizePolicy)
        self.ZZ_NORMATIVA_SISMICAID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_NORMATIVA_SISMICAID.setObjectName("ZZ_NORMATIVA_SISMICAID")
        self.gridLayout_3.addWidget(self.ZZ_NORMATIVA_SISMICAID, 6, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 11, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.DIA_N_PERMESSO = QtGui.QLineEdit(self.groupBox)
        self.DIA_N_PERMESSO.setMaxLength(2000)
        self.DIA_N_PERMESSO.setObjectName("DIA_N_PERMESSO")
        self.gridLayout.addWidget(self.DIA_N_PERMESSO, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setIndent(40)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.DIA_DATA_PERMESSO = QtGui.QDateEdit(self.groupBox)
        self.DIA_DATA_PERMESSO.setCalendarPopup(True)
        self.DIA_DATA_PERMESSO.setDate(QtCore.QDate(2000, 9, 1))
        self.DIA_DATA_PERMESSO.setObjectName("DIA_DATA_PERMESSO")
        self.gridLayout.addWidget(self.DIA_DATA_PERMESSO, 0, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 10, 0, 1, 2)
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 7, 0, 1, 1)
        self.DESCRIZ_INTERV = QtGui.QLineEdit(Form)
        self.DESCRIZ_INTERV.setMaxLength(2000)
        self.DESCRIZ_INTERV.setObjectName("DESCRIZ_INTERV")
        self.gridLayout_3.addWidget(self.DESCRIZ_INTERV, 7, 1, 1, 1)
        self.SCHEDA_EDIFICIOID = QtGui.QLineEdit(Form)
        self.SCHEDA_EDIFICIOID.setObjectName("SCHEDA_EDIFICIOID")
        self.gridLayout_3.addWidget(self.SCHEDA_EDIFICIOID, 12, 0, 1, 2)
        self.INTERVENTO_IN_CORSO = QtGui.QCheckBox(Form)
        self.INTERVENTO_IN_CORSO.setObjectName("INTERVENTO_IN_CORSO")
        self.gridLayout_3.addWidget(self.INTERVENTO_IN_CORSO, 8, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.EPOCA_COSTRUTTIVA.setTitle(QtGui.QApplication.translate("Form", "Periodo di impianto", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Anno progettazione", None, QtGui.QApplication.UnicodeUTF8))
        self.ANNO_PROGETTAZIONE.setDisplayFormat(QtGui.QApplication.translate("Form", "yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Qualità dell\'informazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Categoria di intervento", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Normativa sismica di riferimento", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Permesso DIA", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Num.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.DIA_DATA_PERMESSO.setDisplayFormat(QtGui.QApplication.translate("Form", "dd/MM/yyyy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Descrizione dell\'intervento", None, QtGui.QApplication.UnicodeUTF8))
        self.INTERVENTO_IN_CORSO.setText(QtGui.QApplication.translate("Form", "Intervento in corso", None, QtGui.QApplication.UnicodeUTF8))

from ..GrpEpocaCostruttiva import GrpEpocaCostruttiva
