# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/wdgStrutturePortantiVerticali.ui'
#
# Created: Wed Nov 24 15:49:43 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(435, 445)
        self.gridLayout_2 = QtGui.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.ZZ_QUALITA_INFORMAZIONEID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_QUALITA_INFORMAZIONEID.sizePolicy().hasHeightForWidth())
        self.ZZ_QUALITA_INFORMAZIONEID.setSizePolicy(sizePolicy)
        self.ZZ_QUALITA_INFORMAZIONEID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_QUALITA_INFORMAZIONEID.setObjectName("ZZ_QUALITA_INFORMAZIONEID")
        self.gridLayout_2.addWidget(self.ZZ_QUALITA_INFORMAZIONEID, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 2, 0, 1, 1)
        self.ZZ_STATO_CONSERVAZIONE_STRUTTURALEID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_STATO_CONSERVAZIONE_STRUTTURALEID.sizePolicy().hasHeightForWidth())
        self.ZZ_STATO_CONSERVAZIONE_STRUTTURALEID.setSizePolicy(sizePolicy)
        self.ZZ_STATO_CONSERVAZIONE_STRUTTURALEID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_STATO_CONSERVAZIONE_STRUTTURALEID.setObjectName("ZZ_STATO_CONSERVAZIONE_STRUTTURALEID")
        self.gridLayout_2.addWidget(self.ZZ_STATO_CONSERVAZIONE_STRUTTURALEID, 2, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.ZZ_APPARECCHIATURA_MURARIAID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_APPARECCHIATURA_MURARIAID.sizePolicy().hasHeightForWidth())
        self.ZZ_APPARECCHIATURA_MURARIAID.setSizePolicy(sizePolicy)
        self.ZZ_APPARECCHIATURA_MURARIAID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_APPARECCHIATURA_MURARIAID.setObjectName("ZZ_APPARECCHIATURA_MURARIAID")
        self.gridLayout_2.addWidget(self.ZZ_APPARECCHIATURA_MURARIAID, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.ZZ_INCATENAMENTIID = QtGui.QComboBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_INCATENAMENTIID.sizePolicy().hasHeightForWidth())
        self.ZZ_INCATENAMENTIID.setSizePolicy(sizePolicy)
        self.ZZ_INCATENAMENTIID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_INCATENAMENTIID.setObjectName("ZZ_INCATENAMENTIID")
        self.gridLayout_2.addWidget(self.ZZ_INCATENAMENTIID, 4, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.ZZ_TAMPONATURE_DISTRIBUZIONEID = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_TAMPONATURE_DISTRIBUZIONEID.sizePolicy().hasHeightForWidth())
        self.ZZ_TAMPONATURE_DISTRIBUZIONEID.setSizePolicy(sizePolicy)
        self.ZZ_TAMPONATURE_DISTRIBUZIONEID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_TAMPONATURE_DISTRIBUZIONEID.setObjectName("ZZ_TAMPONATURE_DISTRIBUZIONEID")
        self.gridLayout.addWidget(self.ZZ_TAMPONATURE_DISTRIBUZIONEID, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.ZZ_TAMPONATURE_TIPOLOGIAID = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_TAMPONATURE_TIPOLOGIAID.sizePolicy().hasHeightForWidth())
        self.ZZ_TAMPONATURE_TIPOLOGIAID.setSizePolicy(sizePolicy)
        self.ZZ_TAMPONATURE_TIPOLOGIAID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_TAMPONATURE_TIPOLOGIAID.setObjectName("ZZ_TAMPONATURE_TIPOLOGIAID")
        self.gridLayout.addWidget(self.ZZ_TAMPONATURE_TIPOLOGIAID, 1, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.ZZ_TAMPONATURE_PRESENZA_PIANO_DEBOLEID = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ZZ_TAMPONATURE_PRESENZA_PIANO_DEBOLEID.sizePolicy().hasHeightForWidth())
        self.ZZ_TAMPONATURE_PRESENZA_PIANO_DEBOLEID.setSizePolicy(sizePolicy)
        self.ZZ_TAMPONATURE_PRESENZA_PIANO_DEBOLEID.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.ZZ_TAMPONATURE_PRESENZA_PIANO_DEBOLEID.setObjectName("ZZ_TAMPONATURE_PRESENZA_PIANO_DEBOLEID")
        self.gridLayout.addWidget(self.ZZ_TAMPONATURE_PRESENZA_PIANO_DEBOLEID, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 5, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(20, 25, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ZZ_TIPOLOGIA_COSTRUTTIVAID = MultipleChoiseTipologiaCostruttivaVerticale(self.groupBox)
        self.ZZ_TIPOLOGIA_COSTRUTTIVAID.setObjectName("ZZ_TIPOLOGIA_COSTRUTTIVAID")
        self.gridLayout_3.addWidget(self.ZZ_TIPOLOGIA_COSTRUTTIVAID, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Qualità informazione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Stato conservazione strutturale", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Apparecchiatura muraria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Incatenamenti", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Tamponature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Distribuzione", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "Tipologia", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Presenza piano debole", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Tipologia costruttiva", None, QtGui.QApplication.UnicodeUTF8))

from ..MultipleChoiseTipologiaCostruttivaVerticale import MultipleChoiseTipologiaCostruttivaVerticale
